support 'stop'

diff --git a/bin/workerd b/bin/workerd
--- a/bin/workerd
+++ b/bin/workerd
@@ -26,15 +26,15 @@ start() {
 
 stop() {
     
-    # make sure we're actually running.
-     ./bin/jexec peregrine.worker.WaitForDaemon 2> /dev/null $args 
+    ./bin/jexec peregrine.worker.Main $args > /dev/null 2> /dev/null
     result=$?
 
-    # yup... we're up and running, so stop and return.
-    if [ "$result" = "0" ]; then
-        echo running
+    if [ "$result" != "0" ]; then
+        echo "FAILED to stop daemon"
     fi
-   
+
+    exit $result
+
 }
 
 args=$@
